# Generated by Django 3.1.7 on 2021-03-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mangas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Cód.')),
                ('site_nome', models.CharField(default='', max_length=200, verbose_name='Nome do Site')),
                ('url_nome', models.CharField(default='', max_length=200, verbose_name='Url do Site')),
                ('genero', models.CharField(default='', max_length=200, verbose_name='Url do Site')),
            ],
        ),
    ]
