# Generated by Django 3.1.7 on 2021-03-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela', '0002_auto_20210301_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='sus',
            name='url_nome',
            field=models.CharField(default='', max_length=200, verbose_name='Url do Site'),
        ),
    ]
